name: Main
on: [push]

jobs:
  run-tests-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install packages
        run: npm install
      - name: Test and build
        run: npm run build-production