name: Main
on:
  push:
  schedule:
    - cron: '0 23 * * *'

jobs:
  run-tests-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install packages
        run: npm install
      - name: Download results-last-runs.json
        uses: prewk/s3-cp-action@master
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: eu-west-2
          SOURCE: ${{ secrets.AWS_BUCKET }}/_data/results-last-runs.json
          DEST: ./_data/results-last-runs.json
      - name: Download results data
        uses: prewk/s3-cp-action@master
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: eu-west-2
          SOURCE: ${{ secrets.AWS_BUCKET }}/_data/results
          DEST: ./_data/results
      - name: Test and build
        run: npm run build-production
      - uses: jsmrcaga/action-netlify-deploy@master
        with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_DEPLOY_MESSAGE: "Prod deploy v${{ github.ref }}"
          NETLIFY_DEPLOY_TO_PROD: true
          build_directory: _site
      - name: Upload results-last-runs.json
        uses: tpaschalis/s3-sync-action@master
        env:
          FILE: ./_data/results-last-runs.json
          AWS_REGION: eu-west-2
          AWS_S3_BUCKET: ${{ secrets.AWS_BUCKET }}/_data/results-last-runs.json
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SOURCE: ./_data/results-last-runs.json
          DEST: s3://${{ secrets.AWS_BUCKET }}/_data/results-last-runs.json
      - name: Upload results data
        uses: jakejarvis/s3-sync-action@master
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY_ID }}
          AWS_S3_BUCKET: ${{ secrets.AWS_BUCKET }}/_data/results
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: eu-west-2
          SOURCE_DIR: ./_data/results
