name: Main
on:
  push:
  schedule:
    - cron: '0 23 * * *'

jobs:
  run-tests-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install packages
        run: npm install

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - name: Download results-last-runs.json from S3
        run: |
          aws s3 cp s3://${{ secrets.AWS_BUCKET }}/_data/results-last-runs.json ./_data/results-last-runs.json

      - name: Download results data from S3
        run: |
          aws s3 cp s3://${{ secrets.AWS_BUCKET }}/_data/results ./_data/results --recursive

      - name: Test and build
        run: npm run build-production
      - uses: jsmrcaga/action-netlify-deploy@master
        with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_DEPLOY_MESSAGE: "Prod deploy v${{ github.ref }}"
          NETLIFY_DEPLOY_TO_PROD: true
          build_directory: _site

      - name: Upload results-last-runs.json to S3
        run: |
          aws s3 sync ./_data/results-last-runs.json s3://${{ secrets.AWS_BUCKET }}/_data/results-last-runs.json

      - name: Upload results data to S3
        run: |
          aws s3 sync ./_data/results s3://${{ secrets.AWS_BUCKET }}/_data/results

